# Generated by Django 3.1.5 on 2021-04-25 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(150)]),
        ),
    ]
