# Generated by Django 3.1.5 on 2021-04-25 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210425_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(55)]),
        ),
    ]
